name: Sync Translations
on:
  schedule:
    - cron: '0 12 * * MON'  # Every Monday at noon
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync {{ cookiecutter.project_name }} translations
        uses: Scientific-Python-Translations/translations-sync@main
        with:
          # Provided by user
          crowdin-project: "{{ cookiecutter.project_name }}"
          source-repo: "{{ cookiecutter.__source_repo }}"
          source-folder: "{{ cookiecutter.__source_folder }}"
          source-ref: "{{ cookiecutter.source_ref }}"
          translations-repo: "{{ cookiecutter.translations_repo }}"
          translations-folder: "{{ cookiecutter.translations_folder }}"
          translations-ref: "{{ cookiecutter.translations_ref }}"
          translation-percentage: "{{ cookiecutter.translation_percentage }}"
          approval-percentage: "{{ cookiecutter.approval_percentage }}"
          use-precommit: "{{ cookiecutter.use_precommit }}"
          # Provided by organization secrets
          gpg-private-key: {% raw %}${{ secrets.GPG_PRIVATE_KEY }}{% endraw %}
          passphrase: {% raw %}${{ secrets.PASSPHRASE }}{% endraw %}
          token: {% raw %}${{ secrets.TOKEN }}{% endraw %}
          crowdin-token: {% raw %}${{ secrets.CROWDIN_TOKEN }}{% endraw %}
