name: Sync Translations
on:
  schedule:
    - cron: '0 12 * * MON'  # Every Monday at noon
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync {{ cookiecutter.project_name }} translations
        uses: Scientific-Python-Translations/translations-sync@main
        with:
          crowdin-project: "{{ cookiecutter.project_name }}"
          source-repo: "{{ cookiecutter.__source_repo }}"
          source-path: "{{ cookiecutter.source_path }}"
          source-ref: "{{ cookiecutter.source_ref }}"
          translations-repo: "{{ cookiecutter.translations_repo }}"
          translations-path: "{{ cookiecutter.translations_path }}"
          translations-source-path: "{{ cookiecutter.translations_source_path }}"
          translations-ref: "{{ cookiecutter.translations_ref }}"
          translation-percentage: "{{ cookiecutter.translation_percentage }}"
          approval-percentage: "{{ cookiecutter.approval_percentage }}"
          use-precommit: "{{ cookiecutter.use_precommit }}"
          create-toml-file: "{{ cookiecutter.create_toml_file }}"
          create-upstream-pr: "{{ cookiecutter.create_upstream_pr }}"
          auto-merge: "{{ cookiecutter.auto_merge }}"
          # These are provided by the Scientific Python Project and allow
          # automation with bots
          gpg-private-key: {% raw %}${{ secrets.GPG_PRIVATE_KEY }}{% endraw %}
          passphrase: {% raw %}${{ secrets.PASSPHRASE }}{% endraw %}
          token: {% raw %}${{ secrets.TOKEN }}{% endraw %}
          crowdin-token: {% raw %}${{ secrets.CROWDIN_TOKEN }}{% endraw %}
